### ISSUE TITLE
cant open get to the installer PHP Fatal error:  Uncaught Error: Class "Locale" not found

### ISSUE THREAD

**Issue by syauqielr** [khodakhah/nodcms#72]
error after installing via composer and navigate to public folder get HTTP ERROR 500
XAMPP error.log showing this

`[Tue Nov 30 01:19:56.573118 2021] [php:error] [pid 7312:tid 1884] [client ::1:3595] PHP Fatal error:  Uncaught Error: Class "Locale" not found in C:\\xampp\\htdocs\\nodcms\\system\\HTTP\\IncomingRequest.php:448\nStack trace:\n#0 C:\\xampp\\htdocs\\nodcms\\system\\HTTP\\IncomingRequest.php(186): CodeIgniter\\HTTP\\IncomingRequest->setLocale('en')\n#1 C:\\xampp\\htdocs\\nodcms\\system\\HTTP\\IncomingRequest.php(169): CodeIgniter\\HTTP\\IncomingRequest->detectLocale(Object(Config\\App))\n#2 C:\\xampp\\htdocs\\nodcms\\system\\Config\\Services.php(467): CodeIgniter\\HTTP\\IncomingRequest->__construct(Object(Config\\App), Object(CodeIgniter\\HTTP\\URI), '', Object(CodeIgniter\\HTTP\\UserAgent))\n#3 C:\\xampp\\htdocs\\nodcms\\system\\Config\\BaseService.php(189): CodeIgniter\\Config\\Services::request(Object(Config\\App), false)\n#4 C:\\xampp\\htdocs\\nodcms\\system\\Config\\Services.php(458): CodeIgniter\\Config\\BaseService::getSharedInstance('request', NULL)\n#5 C:\\xampp\\htdocs\\nodcms\\system\\Config\\Services.php(238): CodeIgniter\\Config\\Services::request()\n#6 C:\\xampp\\htdocs\\nodcms\\system\\Config\\BaseService.php(189): CodeIgniter\\Config\\Services::exceptions(Object(Config\\Exceptions), NULL, NULL, false)\n#7 C:\\xampp\\htdocs\\nodcms\\system\\Config\\Services.php(234): CodeIgniter\\Config\\BaseService::getSharedInstance('exceptions', NULL, NULL, NULL)\n#8 C:\\xampp\\htdocs\\nodcms\\system\\CodeIgniter.php(173): CodeIgniter\\Config\\Services::exceptions()\n#9 C:\\xampp\\htdocs\\nodcms\\system\\bootstrap.php(146): CodeIgniter\\CodeIgniter->initialize()\n#10 C:\\xampp\\htdocs\\nodcms\\public\\index.php(66): require('C:\\\\xampp\\\\htdocs...')\n#11 {main}\n  thrown in C:\\xampp\\htdocs\\nodcms\\system\\HTTP\\IncomingRequest.php on line 448, referer: https://localhost/nodcms/`

**Comment by syauqielr** [comment]
solved by enabling php_intl extension in php.ini
